import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { PassThrough, Transform } from 'node:stream';
import { Queue, Worker } from 'bullmq';
import { createEvidencePackageJob, createIngestionJob, createVectorCleanupJob, deleteDocumentVectors, EVIDENCE_PACKAGE_QUEUE, INGESTION_QUEUE, VECTOR_CLEANUP_QUEUE } from '@ca-dcc/shared';
import pg from 'pg';
import { chunkParsedSections } from './chunking.js';
import { loadConfig } from './config.js';
import { embedTexts, indexChunks } from './indexer.js';
import { parseDocument } from './parser.js';
import { createDocumentStorage } from './storage.js';

const require = createRequire(import.meta.url);
const archiver = require('archiver');
const { Pool } = pg;
const config = loadConfig();
const database = new Pool({ connectionString: config.databaseUrl });
const storage = createDocumentStorage(config);
const cleanupQueue = new Queue(VECTOR_CLEANUP_QUEUE, { connection: { url: config.redisUrl } });
const evidencePackageQueue = new Queue(EVIDENCE_PACKAGE_QUEUE, { connection: { url: config.redisUrl } });
